
import AppFooter from "@/components/app-footer";
import AppHeader from "@/components/app-header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <AppHeader />
      <main>{children}</main>
      <AppFooter />
    </div>
  );
}
